/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *dspbang_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _dspbang {
   t_object x_obj;
   t_outlet * x_outlet_output_bang;
} t_dspbang;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * dspbang_new(void);// Constructor
void dspbang_destroy(t_dspbang *x); //Destructor
static t_int * dspbang_perform(t_int *w); //Perform function
static void dspbang_dsp(t_dspbang *x, t_signal **sp); //DSP function

// ---------------------------------------------------
// Perform
// ---------------------------------------------------
static t_int * dspbang_perform(t_int *w){
   t_dspbang *x = (t_dspbang *)(w[1]);
   outlet_bang(x->x_outlet_output_bang);
   return (w + 2); // proximo bloco
}

// ---------------------------------------------------
// DSP Function
// ---------------------------------------------------
static void dspbang_dsp(t_dspbang *x, t_signal **sp){
   dsp_add(dspbang_perform, 1, x);
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * dspbang_new(void){
   t_dspbang *x = (t_dspbang *) pd_new(dspbang_class);
   x->x_outlet_output_bang = outlet_new(&x->x_obj, gensym("bang"));
   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void dspbang_destroy(t_dspbang *x) {
   post("You say good bye and I say hello");
   outlet_free(x->x_outlet_output_bang);
}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void dspbang_tilde_setup(void) {
   dspbang_class = class_new(gensym("dspbang~"),
      (t_newmethod) dspbang_new, // Constructor
      (t_method) dspbang_destroy, // Destructor
      sizeof (t_dspbang),
      CLASS_NOINLET,
      0);//Must always ends with a zero

   class_addmethod(dspbang_class, (t_method) dspbang_dsp, gensym("dsp"), 0);
}
// EOF---------------------------------------------------
