/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *dsponbang_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _dsponbang {
   t_object x_obj;
   t_outlet * x_outlet_output_bang;
   t_outlet * x_outlet_dsp_0;
} t_dsponbang;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * dsponbang_new(void);// Constructor
void dsponbang_destroy(t_dsponbang *x); //Destructor
static void dsponbang_dsp(t_dsponbang *x, t_signal **sp); //DSP function

// ---------------------------------------------------
// DSP Function
// ---------------------------------------------------
static void dsponbang_dsp(t_dsponbang *x, t_signal **sp){
   (void) sp;
   outlet_bang(x->x_outlet_output_bang);
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * dsponbang_new(void){
   t_dsponbang *x = (t_dsponbang *) pd_new(dsponbang_class);
   x->x_outlet_output_bang = outlet_new(&x->x_obj, gensym("bang"));
   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void dsponbang_destroy(t_dsponbang *x) {
   outlet_free(x->x_outlet_output_bang);
}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void dsponbang_tilde_setup(void) {
   dsponbang_class = class_new(gensym("dsponbang~"),
      (t_newmethod) dsponbang_new, // Constructor
      (t_method) dsponbang_destroy, // Destructor
      sizeof (t_dsponbang),
      CLASS_NOINLET,
      0);//Must always ends with a zero

   class_addmethod(dsponbang_class, (t_method) dsponbang_dsp, gensym("dsp"), 0);
}
// EOF---------------------------------------------------
