/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *example13_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _example13 {
   t_object x_obj;
   t_inlet * x_inlet_dsp_0;
   t_inlet * x_inlet_dsp_1;
   t_inlet * x_inlet_dsp_2;
   t_inlet * x_inlet_dsp_3;

   t_outlet * x_outlet_dsp_0;
   t_outlet * x_outlet_dsp_1;
   t_outlet * x_outlet_dsp_2;
   t_outlet * x_outlet_dsp_3;

} t_example13;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * example13_new(void);// Constructor
void example13_destroy(t_example13 *x); //Destructor
static t_int * example13_perform(t_int *w); //Perform function
static void example13_dsp(t_example13 *x, t_signal **sp); //DSP function

// ---------------------------------------------------
// Perform
// ---------------------------------------------------
static t_int * example13_perform(t_int *w){
   t_example13 *x = (t_example13 *)(w[1]);
   int n = (int)(w[2]);
   t_float *in1 = (t_float *)(w[3]);
   t_float *in2 = (t_float *)(w[4]);
   t_float *in3 = (t_float *)(w[5]);
   t_float *in4 = (t_float *)(w[6]);
   t_float *out1 = (t_float *)(w[7]);
   t_float *out2 = (t_float *)(w[8]);
   t_float *out3 = (t_float *)(w[9]);
   t_float *out4 = (t_float *)(w[10]);
   return (w + 11); // proximo bloco
}

// ---------------------------------------------------
// DSP Function
// ---------------------------------------------------
static void example13_dsp(t_example13 *x, t_signal **sp){
   dsp_add(example13_perform, 10, x, sp[0]->s_n, sp[0]->s_vec, sp[1]->s_vec, sp[2]->s_vec, sp[3]->s_vec, sp[4]->s_vec, sp[5]->s_vec, sp[6]->s_vec, sp[7]->s_vec);
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * example13_new(void){
   t_example13 *x = (t_example13 *) pd_new(example13_class);

   x->x_inlet_dsp_0 = inlet_new(&x->x_obj, &x->x_obj.ob_pd, &s_signal, &s_signal);
   x->x_inlet_dsp_1 = inlet_new(&x->x_obj, &x->x_obj.ob_pd, &s_signal, &s_signal);
   x->x_inlet_dsp_2 = inlet_new(&x->x_obj, &x->x_obj.ob_pd, &s_signal, &s_signal);
   x->x_inlet_dsp_3 = inlet_new(&x->x_obj, &x->x_obj.ob_pd, &s_signal, &s_signal);

   x->x_outlet_dsp_0 = outlet_new(&x->x_obj, &s_signal);
   x->x_outlet_dsp_1 = outlet_new(&x->x_obj, &s_signal);
   x->x_outlet_dsp_2 = outlet_new(&x->x_obj, &s_signal);
   x->x_outlet_dsp_3 = outlet_new(&x->x_obj, &s_signal);

   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void example13_destroy(t_example13 *x) {
   post("You say good bye and I say hello");
   inlet_free(x->x_inlet_dsp_0);
   inlet_free(x->x_inlet_dsp_1);
   inlet_free(x->x_inlet_dsp_2);
   inlet_free(x->x_inlet_dsp_3);

   outlet_free(x->x_outlet_dsp_0);
   outlet_free(x->x_outlet_dsp_1);
   outlet_free(x->x_outlet_dsp_2);
   outlet_free(x->x_outlet_dsp_3);

}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void example13_tilde_setup(void) {
   example13_class = class_new(gensym("example13~"),
      (t_newmethod) example13_new, // Constructor
      (t_method) example13_destroy, // Destructor
      sizeof (t_example13),
      CLASS_NOINLET,
      0);//Must always ends with a zero

   class_addmethod(example13_class, (t_method) example13_dsp, gensym("dsp"), 0);
}
// EOF---------------------------------------------------
