/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *example12_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _example12 {
   t_object x_obj;
   t_outlet * x_outlet_dsp_0;
   t_outlet * x_outlet_dsp_1;
   t_outlet * x_outlet_dsp_2;
   t_outlet * x_outlet_dsp_3;

} t_example12;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * example12_new(void);// Constructor
void example12_destroy(t_example12 *x); //Destructor
static t_int * example12_perform(t_int *w); //Perform function
static void example12_dsp(t_example12 *x, t_signal **sp); //DSP function

// ---------------------------------------------------
// Perform
// ---------------------------------------------------
static t_int * example12_perform(t_int *w){
   t_example12 *x = (t_example12 *)(w[1]);
   int n = (int)(w[2]);
   t_float *out1 = (t_float *)(w[3]);
   t_float *out2 = (t_float *)(w[4]);
   t_float *out3 = (t_float *)(w[5]);
   t_float *out4 = (t_float *)(w[6]);
   return (w + 7); // proximo bloco
}

// ---------------------------------------------------
// DSP Function
// ---------------------------------------------------
static void example12_dsp(t_example12 *x, t_signal **sp){
   dsp_add(example12_perform, 6, x, sp[0]->s_n, sp[0]->s_vec, sp[1]->s_vec, sp[2]->s_vec, sp[3]->s_vec);
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * example12_new(void){
   t_example12 *x = (t_example12 *) pd_new(example12_class);

   x->x_outlet_dsp_0 = outlet_new(&x->x_obj, &s_signal);
   x->x_outlet_dsp_1 = outlet_new(&x->x_obj, &s_signal);
   x->x_outlet_dsp_2 = outlet_new(&x->x_obj, &s_signal);
   x->x_outlet_dsp_3 = outlet_new(&x->x_obj, &s_signal);

   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void example12_destroy(t_example12 *x) {
   post("You say good bye and I say hello");
   outlet_free(x->x_outlet_dsp_0);
   outlet_free(x->x_outlet_dsp_1);
   outlet_free(x->x_outlet_dsp_2);
   outlet_free(x->x_outlet_dsp_3);

}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void example12_tilde_setup(void) {
   example12_class = class_new(gensym("example12~"),
      (t_newmethod) example12_new, // Constructor
      (t_method) example12_destroy, // Destructor
      sizeof (t_example12),
      CLASS_DEFAULT,
      0);//Must always ends with a zero

   class_addmethod(example12_class, (t_method) example12_dsp, gensym("dsp"), 0);
}
// EOF---------------------------------------------------
