/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *first_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _first {
   t_object x_obj;
   t_inlet * x_inlet_dsp_0;

} t_first;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * first_new(void);// Constructor
void first_destroy(t_first *x); //Destructor
static t_int * first_perform(t_int *w); //Perform function
static void first_dsp(t_first *x, t_signal **sp); //DSP function

// ---------------------------------------------------
// Perform
// ---------------------------------------------------
static t_int * first_perform(t_int *w){
   t_first *x = (t_first *)(w[1]);
   int n = (int)(w[2]);
   t_float *in1 = (t_float *)(w[3]);
   return (w + 4); // proximo bloco
}

// ---------------------------------------------------
// DSP Function
// ---------------------------------------------------
static void first_dsp(t_first *x, t_signal **sp){
   dsp_add(first_perform, 3, x, sp[0]->s_n, sp[0]->s_vec);
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * first_new(void){
   t_first *x = (t_first *) pd_new(first_class);

   x->x_inlet_dsp_0 = inlet_new(&x->x_obj, &x->x_obj.ob_pd, &s_signal, &s_signal);

   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void first_destroy(t_first *x) {
   post("You say good bye and I say hello");
   inlet_free(x->x_inlet_dsp_0);

}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void first_tilde_setup(void) {
   first_class = class_new(gensym("first~"),
      (t_newmethod) first_new, // Constructor
      (t_method) first_destroy, // Destructor
      sizeof (t_first),
      CLASS_DEFAULT,
      0);//Must always ends with a zero

   class_addmethod(first_class, (t_method) first_dsp, gensym("dsp"), 0);
}
// EOF---------------------------------------------------
