/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *mailman_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _mailman {
   t_object x_obj;
   int argc;
   t_symbol ** messages;
} t_mailman;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * mailman_new(t_symbol *s, int argc, t_atom *argv1);// Constructor
void mailman_destroy(t_mailman *x); //Destructor
void mailman_bang(t_mailman *x); // Message function

// ---------------------------------------------------
// mailman_bang
// ---------------------------------------------------
void mailman_bang(t_mailman *x){
   int i = 0;
   for(; i < x->argc ; i++){
      if (x->messages[i]->s_thing)
         pd_bang(x->messages[i]->s_thing);
   }
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * mailman_new(t_symbol *s, int argc, t_atom *argv){
   (void) s;
   t_mailman *x = (t_mailman *) pd_new(mailman_class);
   int i = 0;
   int counter = 0;
   for(; i < argc ; i++){
      if((argv + i)->a_type == A_SYMBOL)
         counter++;
   }
   x->messages = getbytes(counter * sizeof(t_symbol *));
   counter = 0;
   for(i = 0; i < argc ; i++){
      if((argv + i)->a_type == A_SYMBOL){
         x->messages[counter] = atom_getsymbol(argv + i);
         counter++;
      }
   }
   x->argc = counter;
   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void mailman_destroy(t_mailman *x) {
   post("You say good bye and I say hello");
}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void mailman_setup(void) {
   mailman_class = class_new(gensym("mailman"),
      (t_newmethod) mailman_new, // Constructor
      (t_method) mailman_destroy, // Destructor
      sizeof (t_mailman),
      CLASS_DEFAULT,
      A_GIMME,
      0);//Must always ends with a zero

   class_addmethod(mailman_class, (t_method) mailman_bang, gensym("bang"), 0);
}
// EOF---------------------------------------------------
