/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *outlet_dinamico_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _outlet_dinamico {
   t_object x_obj;
   t_outlet ** my_outlets; // Defines a outlet
   t_float outlet_count;
} t_outlet_dinamico;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * outlet_dinamico_new(t_floatarg outlet_count_arg);// Constructor
void outlet_dinamico_destroy(t_outlet_dinamico *x); //Destructor

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * outlet_dinamico_new(t_floatarg outlet_count_arg){
   t_outlet_dinamico *x = (t_outlet_dinamico *) pd_new(outlet_dinamico_class);

   x->outlet_count = outlet_count_arg;
   int i = 0;
   post("Outlet count: %d", x->outlet_count);
   x->my_outlets = getbytes(x->outlet_count * sizeof(t_outlet*));
   for(i = 0 ; i < (int) x->outlet_count; i++){
      x->my_outlets[i] = outlet_new(&x->x_obj, gensym("bang"));
   }
   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void outlet_dinamico_destroy(t_outlet_dinamico *x) {
   int i = 0;
   for(i = 0 ; i < (int) x->outlet_count; i++){
     outlet_free(x->my_outlets[i]);
   }
}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void outlet_dinamico_setup(void) {
   outlet_dinamico_class = class_new(gensym("outlet_dinamico"),
      (t_newmethod) outlet_dinamico_new, // Constructor
      (t_method) outlet_dinamico_destroy, // Destructor
      sizeof (t_outlet_dinamico),
      CLASS_NOINLET,
      A_DEFFLOAT, //Outlet_count
      0);//Must always ends with a zero

}
// EOF---------------------------------------------------
