/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include <string.h>
#include "m_pd.h"
#include "g_canvas.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *tcl_prompt_class;
t_widgetbehavior tcl_prompt_widgetbehavior;
// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _tcl_prompt {
   t_object x_obj;
   char *text;
   t_glist *glist;
   t_outlet * x_outlet_symbol;
} t_tcl_prompt;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * tcl_prompt_new(t_symbol *s, int argc, t_atom *argv1);// Constructor
void tcl_prompt_destroy(t_tcl_prompt *x); //Destructor
void tcl_prompt_apply(t_tcl_prompt *x, t_symbol *s, int argc, t_atom *argv);
void tcl_prompt_bang_method(t_tcl_prompt *x);// Active inlet function
//GUI stuff
static void tcl_prompt_getrect(t_gobj *z, t_glist *glist, int *xp1, int *yp1, int *xp2, int *yp2);
static void tcl_prompt_vis(t_gobj *z, t_glist *glist, int vis);
static void tcl_prompt_displace(t_gobj *z, t_glist *glist,int dx, int dy);
static void tcl_prompt_activate(t_gobj *x, struct _glist *glist, int state);
static void tcl_prompt_select(t_gobj *z, t_glist *glist, int state);
static int tcl_prompt_click(t_gobj *z, struct _glist *glist, int xpix, int ypix, int shift, int alt, int dbl, int doit);
static void tcl_prompt_delete(t_gobj *z, t_glist *glist);
static void tcl_prompt_save(t_gobj *c, t_binbuf *b);

// ---------------------------------------------------
// tcl_prompt_apply
// ---------------------------------------------------
void tcl_prompt_apply(t_tcl_prompt *x, t_symbol *s, int argc, t_atom *argv){
   (void) s;
   strcpy(x->text, "\0");
   int i = 0;
   for(i = 0; i < argc; i++){
      if(argv[i].a_type == A_SYMBOL)
         strcat(x->text, atom_getsymbolarg(i, argc, argv)->s_name);
      if(argv[i].a_type == A_FLOAT){
         char temp[256];
         sprintf(temp, "%f", atom_getfloatarg(i, argc, argv));
         strcat(x->text, temp);
         }
      if(i < argc -1)
         strcat(x->text, " ");
   }
   if(strcmp("loading", s->s_name) != 0){
      sys_vgui(".x%lx.c.t%lx configure -state normal ;\n",
         x->glist,
         x);
      sys_vgui(".x%lx.c.t%lx delete 1.0 end ;\n",
         x->glist,
         x);
      sys_vgui(".x%lx.c.t%lx insert end \"%s\";\n",
         x->glist,
         x,
         x->text);
      tcl_prompt_bang_method(x);
   }
}

// ---------------------------------------------------
// tcl_prompt_bang
// ---------------------------------------------------
void tcl_prompt_bang_method(t_tcl_prompt *x){
      sys_vgui("\
            set arg [.x%lx.c.t%lx get 1.0 {end -1c}] \n\
            set arg [string map {canvas .x%lx.c} \"$arg\"] \n\
            set arg [string map {obj t%lx} \"$arg\"] \n\
            eval $arg\n\
         \n",
         x->glist,
         x,
         x->glist,
         x
         );
   outlet_symbol(x->x_outlet_symbol, gensym(x->text));
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * tcl_prompt_new(t_symbol *s, int argc, t_atom *argv){
   (void)s;
   t_tcl_prompt *x = (t_tcl_prompt *) pd_new(tcl_prompt_class);
   x->text = getbytes(2048 * 1024);
   x->glist = (t_glist *)canvas_getcurrent();
   char buf[256];
   sprintf(buf,"tcl_prompt%lx", (long unsigned int)x);
   pd_bind(&x->x_obj.ob_pd, gensym(buf));
   tcl_prompt_apply(x, gensym("loading"), argc, argv);
   x->x_outlet_symbol = outlet_new(&x->x_obj, gensym("symbol"));
   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void tcl_prompt_destroy(t_tcl_prompt *x) {
   char buf[256];
   sprintf(buf,"tcl_prompt%lx", (long unsigned int)x);
   pd_unbind(&x->x_obj.ob_pd, gensym(buf));
   outlet_free(x->x_outlet_symbol);
   freebytes(x->text, 2048 * 1024);
}

//GUI stuff ---------------------------------------
// ---------------------------------------------------
// The external GUI rectangle definition
// ---------------------------------------------------
static void tcl_prompt_getrect(t_gobj *z, t_glist *glist, int *xp1, int *yp1, int *xp2, int *yp2){
   // This function is always called. 
   // Better do not put a post here...
   // post("GETRECT");
   (void) glist;
   t_tcl_prompt *x = (t_tcl_prompt *)z;
   *xp1 = x->x_obj.te_xpix;
   *yp1 = x->x_obj.te_ypix - 6;
   *xp2 = x->x_obj.te_xpix + 289;
   *yp2 = x->x_obj.te_ypix + 191;
}
// ---------------------------------------------------
// How to make it visible / invisible
// ---------------------------------------------------
static void tcl_prompt_vis(t_gobj *z, t_glist *glist, int vis){
   t_tcl_prompt *x = (t_tcl_prompt *)z;
   t_canvas * canvas = glist_getcanvas(glist);
   if(vis){ // VISIBLE
      sys_vgui(".x%lx.c create rectangle %d %d %d %d -tags x%lx.c.ret%lx -fill #999999 \n",
         canvas,
         x->x_obj.te_xpix + 1,
         x->x_obj.te_ypix - 5,
         x->x_obj.te_xpix + 289,
         x->x_obj.te_ypix + 189,
         canvas,
         x
         );
      // Text
      sys_vgui("text .x%lx.c.t%lx -width 40 -height 10 -wrap word\n",
         canvas,
         x);
      //load value
      sys_vgui(".x%lx.c.t%lx delete 1.0 end \n",
         x->glist,
         x);
      sys_vgui(".x%lx.c.t%lx insert end \"%s\"\n",
         x->glist,
         x,
         x->text);
      sys_vgui(".x%lx.c create window %d %d -window .x%lx.c.t%lx -tags x%lx.c.t%lx\n",
         canvas,
         x->x_obj.te_xpix + 145,
         x->x_obj.te_ypix + 75,
         canvas,
         x,
         canvas,
         x
         );
      sys_vgui("bind .x%lx.c <1> {+ .x%lx.c.t%lx configure -state disabled}\n",
         canvas,
         canvas,
         x
         );
      sys_vgui("bind .x%lx.c.t%lx <1> {+ .x%lx.c.t%lx configure -state normal}\n",
         canvas,
         x,
         canvas,
         x
         );
      //Button
      sys_vgui("button .x%lx.c.b%lx -text \"Execute\" \
         -command {\
            set arg [.x%lx.c.t%lx get 1.0 {end -1c}] \n\
            pd [concat tcl_prompt%lx apply $arg \\;]\n\
            set arg [string map {canvas .x%lx.c} \"$arg\"] \n\
            set arg [string map {obj t%lx} \"$arg\"] \n\
            eval $arg\n\
            }\
         \n",
         canvas,
         x,
         canvas,
         x,
         x,
         canvas,
         x
         );
      sys_vgui(".x%lx.c create window %d %d -window .x%lx.c.b%lx -tags x%lx.c.b%lx\n",
         canvas,
         x->x_obj.te_xpix + 241,
         x->x_obj.te_ypix + 170,
         canvas,
         x,
         canvas,
         x
         );
   }else{
      sys_vgui(".x%lx.c delete x%lx.c.t%lx\n",
         canvas,
         canvas,
         x);
      sys_vgui(".x%lx.c delete x%lx.c.b%lx\n",
         canvas,
         canvas,
         x);
      sys_vgui(".x%lx.c delete x%lx.c.ret%lx\n",
         canvas,
         canvas,
         x);
   }
}
// ---------------------------------------------------
// what to do when moved
// ---------------------------------------------------
static void tcl_prompt_displace(t_gobj *z, t_glist *glist,int dx, int dy){
   t_canvas * canvas = glist_getcanvas(glist);
   t_tcl_prompt *x = (t_tcl_prompt *)z;
   x->x_obj.te_xpix += dx; // x movement
   x->x_obj.te_ypix += dy; // y movement

   //MOVE selected
   sys_vgui(".x%lx.c move %lxSEL %d %d \n", canvas, x, dx, dy);

   sys_vgui(".x%lx.c coords x%lx.c.ret%lx %d %d %d %d \n",
      canvas,
      canvas,
      x,
      x->x_obj.te_xpix + 1,
      x->x_obj.te_ypix - 4,
      x->x_obj.te_xpix + 289,
      x->x_obj.te_ypix + 189
      );

   //MOVE window
   sys_vgui(".x%x.c coords x%lx.c.t%lx %d %d\n",
      canvas,
      canvas,
      x,
      x->x_obj.te_xpix + 145,
      x->x_obj.te_ypix + 75
      );

   //MOVE window
   sys_vgui(".x%x.c coords x%lx.c.b%lx %d %d\n",
      canvas,
      canvas,
      x,
      x->x_obj.te_xpix + 241,
      x->x_obj.te_ypix + 170
      );

   canvas_fixlinesfor(glist, (t_text *)x);
}
// ---------------------------------------------------
// What to do when active
// ---------------------------------------------------
static void tcl_prompt_activate(t_gobj *x, struct _glist *glist, int state){
   (void)x;
   (void)glist;
   (void)state;
}
// ---------------------------------------------------
// What to do when selected
// ---------------------------------------------------
static void tcl_prompt_select(t_gobj *z, t_glist *glist, int state){
   (void)z;
   (void)glist;
   (void)state;
   t_tcl_prompt *x = (t_tcl_prompt *)z;
   if (state) {
      // We use to draw a blue contour here
      sys_vgui(".x%lx.c.t%lx configure -state disabled\n",
         glist,
         z);
      sys_vgui(".x%x.c create rectangle %d %d %d %d -tags %lxSEL -outline blue\n",
         glist_getcanvas(glist),
         x->x_obj.te_xpix + 1,
         x->x_obj.te_ypix - 4,
         x->x_obj.te_xpix + 289,
         x->x_obj.te_ypix + 189,
         x
         );
   }else {
      // We use to delete the blue contour here
      sys_vgui(".x%lx.c.t%lx configure -state normal\n",
         glist,
         z);
      sys_vgui(".x%x.c delete %lxSEL\n",glist_getcanvas(glist), x);
   }
}
// ---------------------------------------------------
// What to do when clicked
// ---------------------------------------------------
static int tcl_prompt_click(t_gobj *z, struct _glist *glist, int xpix, int ypix, int shift, int alt, int dbl, int doit){
   (void) glist;
   (void)z;
   (void)xpix;
   (void)ypix;
   (void)shift;
   (void)alt;
   (void)dbl;
   (void)doit;
return 0;
}
// ---------------------------------------------------
// What to do when deleted
// ---------------------------------------------------
static void tcl_prompt_delete(t_gobj *z, t_glist *glist){
   t_text *x = (t_text *)z;
   t_canvas * canvas = glist_getcanvas(glist);
   canvas_deletelinesfor(canvas, x);
   sys_vgui(".x%lx.c delete x%lx.c.t%lx\n",
      canvas,
      canvas,
      x);
   sys_vgui(".x%lx.c delete x%lx.c.b%lx\n",
      canvas,
      canvas,
      x);
   sys_vgui(".x%lx.c delete x%lx.c.ret%lx\n",
      canvas,
      canvas,
      x);
   //Something else?
}

// ---------------------------------------------------
// What to do when saved
// ---------------------------------------------------
static void tcl_prompt_save(t_gobj *c, t_binbuf *b){
   t_tcl_prompt *x = (t_tcl_prompt *)c;

   binbuf_addv(b, "ssiiss",
      gensym("#X"),
      gensym("obj"),
      (t_int)x->x_obj.te_xpix,
      (t_int)x->x_obj.te_ypix,
      gensym("tcl_prompt"),
      gensym(x->text));
   binbuf_addv(b, ";");
}

//EOF GUI stuff ---------------------------------------
// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void tcl_prompt_setup(void) {
   tcl_prompt_class = class_new(gensym("tcl_prompt"),
      (t_newmethod) tcl_prompt_new, // Constructor
      (t_method) tcl_prompt_destroy, // Destructor
      sizeof (t_tcl_prompt),
      CLASS_DEFAULT,
      A_GIMME,
      0);//Must always ends with a zero

   class_addmethod(tcl_prompt_class, (t_method) tcl_prompt_apply, gensym("apply"),A_GIMME,  0);
   class_addbang(tcl_prompt_class, tcl_prompt_bang_method);

   sys_gui(" if { [catch {pd}] } {proc pd {args} {pdsend [join $args " "]}}\n");

//   GUI STUFF---------------------------
   tcl_prompt_widgetbehavior.w_getrectfn = tcl_prompt_getrect;
   tcl_prompt_widgetbehavior.w_visfn= tcl_prompt_vis;
   tcl_prompt_widgetbehavior.w_displacefn= tcl_prompt_displace;
   tcl_prompt_widgetbehavior.w_selectfn= tcl_prompt_select;
   tcl_prompt_widgetbehavior.w_activatefn = tcl_prompt_activate;
   tcl_prompt_widgetbehavior.w_deletefn = tcl_prompt_delete;
   tcl_prompt_widgetbehavior.w_clickfn = tcl_prompt_click;
   class_setsavefn(tcl_prompt_class, tcl_prompt_save);
   class_setwidget(tcl_prompt_class, &tcl_prompt_widgetbehavior);
}
// EOF---------------------------------------------------
