/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *teste_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _teste {
   t_object x_obj;
} t_teste;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * teste_new(void);// Constructor
void teste_destroy(t_teste *x); //Destructor

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * teste_new(void){
   t_teste *x = (t_teste *) pd_new(teste_class);

   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void teste_destroy(t_teste *x) {
   post("You say good bye and I say hello");
}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void teste_setup(void) {
   teste_class = class_new(gensym("teste"),
      (t_newmethod) teste_new, // Constructor
      (t_method) teste_destroy, // Destructor
      sizeof (t_teste),
      CLASS_GOBJ,
      0);//Must always ends with a zero

}
// EOF---------------------------------------------------
