/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *canvas_id_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _canvas_id {
   t_object x_obj;
   t_glist * glist;
   int id;
} t_canvas_id;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * canvas_id_new(void);// Constructor
void canvas_id_destroy(t_canvas_id *x); //Destructor
void canvas_id_name_bang_method(t_canvas_id *x);// Active inlet function

// ---------------------------------------------------
// canvas_id_name
// ---------------------------------------------------
void canvas_id_name_bang_method(t_canvas_id *x){
   (void) x;
   post("%lx", x->glist);
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * canvas_id_new(void){
   t_canvas_id *x = (t_canvas_id *) pd_new(canvas_id_class);
   x->glist=(t_glist *)canvas_getcurrent();
   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void canvas_id_destroy(t_canvas_id *x) {
   (void) x;
   post("You say good bye and I say hello");
}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void canvas_id_setup(void) {
   canvas_id_class = class_new(gensym("canvas_id"),
      (t_newmethod) canvas_id_new, // Constructor
      (t_method) canvas_id_destroy, // Destructor
      sizeof (t_canvas_id),
      CLASS_DEFAULT,
      0);//Must always ends with a zero

   class_addbang(canvas_id_class, canvas_id_name_bang_method);
}
// EOF---------------------------------------------------
