/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *counter_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _counter {
   t_object x_obj;
   t_float counter;
   t_outlet * x_outlet_output_float;
} t_counter;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * counter_new(void);// Constructor
void counter_destroy(t_counter *x); //Destructor
void counter_count_bang_method(t_counter *x);// Active inlet function

// ---------------------------------------------------
// counter_count
// ---------------------------------------------------
void counter_count_bang_method(t_counter *x){
   x->counter++;
   outlet_float(x->x_outlet_output_float, x->counter);
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * counter_new(void){
   t_counter *x = (t_counter *) pd_new(counter_class);
   x->counter = 0;
   x->x_outlet_output_float = outlet_new(&x->x_obj, gensym("float"));
   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void counter_destroy(t_counter *x) {
   post("You say good bye and I say hello");
   outlet_free(x->x_outlet_output_float);
}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void counter_setup(void) {
   counter_class = class_new(gensym("counter"),
      (t_newmethod) counter_new, // Constructor
      (t_method) counter_destroy, // Destructor
      sizeof (t_counter),
      CLASS_DEFAULT,
      0);//Must always ends with a zero

   class_addbang(counter_class, counter_count_bang_method);
}
// EOF---------------------------------------------------
