/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *evenodd_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _evenodd {
   t_object x_obj;
   t_float data;
   t_inlet * x_inlet_data_float;
} t_evenodd;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * evenodd_new(void);// Constructor
void evenodd_destroy(t_evenodd *x); //Destructor
void evenodd_bang(t_evenodd *x); // Message function

// ---------------------------------------------------
// evenodd_bang
// ---------------------------------------------------
void evenodd_bang(t_evenodd *x){
   if(((int)x->data) % 2 == 0)
      post("even");
   else
      post("odd");
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * evenodd_new(void){
   t_evenodd *x = (t_evenodd *) pd_new(evenodd_class);
   x->x_inlet_data_float = floatinlet_new(&x->x_obj, &x->data);
   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void evenodd_destroy(t_evenodd *x) {
   post("You say good bye and I say hello");
   inlet_free(x->x_inlet_data_float);
}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void evenodd_setup(void) {
   evenodd_class = class_new(gensym("evenodd"),
      (t_newmethod) evenodd_new, // Constructor
      (t_method) evenodd_destroy, // Destructor
      sizeof (t_evenodd),
      CLASS_DEFAULT,
      0);//Must always ends with a zero

   class_addmethod(evenodd_class, (t_method) evenodd_bang, gensym("bang"), 0);
}
// EOF---------------------------------------------------
