/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *harmonics_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _harmonics {
   t_object x_obj;
   t_inlet * x_inlet_dsp_0;
   t_outlet * x_outlet_dsp_0;
} t_harmonics;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * harmonics_new(void);// Constructor
void harmonics_destroy(t_harmonics *x); //Destructor
static t_int * harmonics_perform(t_int *w); //Perform function
static void harmonics_dsp(t_harmonics *x, t_signal **sp); //DSP function

// ---------------------------------------------------
// Perform
// ---------------------------------------------------
static t_int * harmonics_perform(t_int *w){
//   t_harmonics *x = (t_harmonics *)(w[1]);
   int n = (int)(w[2]), i = 0;
   t_float *in1 = (t_float *)(w[3]);
   t_float *out1 = (t_float *)(w[4]);
   for(i = 0 ; i < n; i++){
      out1[i] = (i % 2)? in1[i + 1] : in1[i - 1] * -1;
   }
   return (w + 5); // proximo bloco
}

// ---------------------------------------------------
// DSP Function
// ---------------------------------------------------
static void harmonics_dsp(t_harmonics *x, t_signal **sp){
   dsp_add(harmonics_perform, 4, x, sp[0]->s_n, sp[0]->s_vec, sp[1]->s_vec);
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * harmonics_new(void){
   t_harmonics *x = (t_harmonics *) pd_new(harmonics_class);

   x->x_inlet_dsp_0 = inlet_new(&x->x_obj, &x->x_obj.ob_pd, &s_signal, &s_signal);
   x->x_outlet_dsp_0 = outlet_new(&x->x_obj, &s_signal);

   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void harmonics_destroy(t_harmonics *x) {
   post("You say good bye and I say hello");
   inlet_free(x->x_inlet_dsp_0);
   outlet_free(x->x_outlet_dsp_0);
}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void harmonics_tilde_setup(void) {
   harmonics_class = class_new(gensym("harmonics~"),
      (t_newmethod) harmonics_new, // Constructor
      (t_method) harmonics_destroy, // Destructor
      sizeof (t_harmonics),
      CLASS_NOINLET,
      0);//Must always ends with a zero

   class_addmethod(harmonics_class, (t_method) harmonics_dsp, gensym("dsp"), 0);
}
// EOF---------------------------------------------------
