/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include <string.h>
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *inverter_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _inverter {
   t_object x_obj;
   t_outlet * x_outlet_inverted_symbol;
} t_inverter;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * inverter_new(void);// Constructor
void inverter_destroy(t_inverter *x); //Destructor
void inverter_input_symbol_method(t_inverter *x, t_symbol *s);// Active inlet function

// ---------------------------------------------------
// inverter_input
// ---------------------------------------------------
void inverter_input_symbol_method(t_inverter *x, t_symbol *s){
   char temp;
   int i = 0;
   for(i = 0; i < (int)(strlen(s->s_name) / 2); i++){
      temp = s->s_name[i];
      s->s_name[i] = s->s_name[strlen(s->s_name) - i - 1];
      s->s_name[strlen(s->s_name) - i - 1] = temp;
   }
   outlet_symbol(x->x_outlet_inverted_symbol, s);
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * inverter_new(void){
   t_inverter *x = (t_inverter *) pd_new(inverter_class);
   x->x_outlet_inverted_symbol = outlet_new(&x->x_obj, gensym("symbol"));
   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void inverter_destroy(t_inverter *x) {
   post("You say good bye and I say hello");
   outlet_free(x->x_outlet_inverted_symbol);
}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void inverter_setup(void) {
   inverter_class = class_new(gensym("inverter"),
      (t_newmethod) inverter_new, // Constructor
      (t_method) inverter_destroy, // Destructor
      sizeof (t_inverter),
      CLASS_DEFAULT,
      0);//Must always ends with a zero

   class_addsymbol(inverter_class, inverter_input_symbol_method);
}
// EOF---------------------------------------------------
