/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *multiplus_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _multiplus {
   t_object x_obj;
   t_float count;
   t_float * values;
   t_outlet ** my_outlets; // Defines a outlet
} t_multiplus;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * multiplus_new(t_floatarg count_arg);// Constructor
void multiplus_destroy(t_multiplus *x); //Destructor
void multiplus_bang(t_multiplus *x); // Message function

// ---------------------------------------------------
// multiplus_bang
// ---------------------------------------------------
void multiplus_bang(t_multiplus *x){
   int i = 0;
   for(; i < (int) x->count ; i++){
      outlet_float(x->my_outlets[i], x->values[i] + 1);
   }
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * multiplus_new(t_floatarg count_arg){
   t_multiplus *x = (t_multiplus *) pd_new(multiplus_class);
   x->count = count_arg;
   x->my_outlets = getbytes(x->count * sizeof(t_outlet*));
   x->values = getbytes(x->count * sizeof(t_float));
   int i = 0;
   for(i = 0 ; i < (int) x->count; i++){
      x->my_outlets[i] = outlet_new(&x->x_obj, gensym("bang"));
      floatinlet_new (&x->x_obj, &x->values[i]);
   }
   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void multiplus_destroy(t_multiplus *x) {
   int i = 0;
   for(i = 0 ; i < (int) x->count; i++){
     outlet_free(x->my_outlets[i]);
   }
}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void multiplus_setup(void) {
   multiplus_class = class_new(gensym("multiplus"),
      (t_newmethod) multiplus_new, // Constructor
      (t_method) multiplus_destroy, // Destructor
      sizeof (t_multiplus),
      CLASS_DEFAULT,
      A_DEFFLOAT,
      0);//Must always ends with a zero

   class_addmethod(multiplus_class, (t_method) multiplus_bang, gensym("bang"), 0);
}
// EOF---------------------------------------------------
