/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"
#include "g_canvas.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *my_circle_class;
t_widgetbehavior my_circle_widgetbehavior; // This represents the external GUI

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _my_circle {
   t_object x_obj;
   t_glist *glist;
   t_int value;
} t_my_circle;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * my_circle_new(void);// Constructor
void my_circle_destroy(t_my_circle *x); //Destructor
//GUI stuff
static void my_circle_getrect(t_gobj *z, t_glist *glist, int *xp1, int *yp1, int *xp2, int *yp2);
static void my_circle_vis(t_gobj *z, t_glist *glist, int vis);
static void my_circle_displace(t_gobj *z, t_glist *glist,int dx, int dy);
static void my_circle_activate(t_gobj *x, struct _glist *glist, int state);
static void my_circle_select(t_gobj *z, t_glist *glist, int state);
static int my_circle_click(t_gobj *z, struct _glist *glist, int xpix, int ypix, int shift, int alt, int dbl, int doit);
static void my_circle_delete(t_gobj *z, t_glist *glist);
static void my_circle_save(t_gobj *c, t_binbuf *b);
static void my_circle_properties(t_gobj *c, t_glist *list);

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * my_circle_new(void){
   t_my_circle *x = (t_my_circle *) pd_new(my_circle_class);
   x->glist = (t_glist *)canvas_getcurrent();
   x->value = 0;
   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void my_circle_destroy(t_my_circle *x) {
   (void)x;
   post("You say good bye and I say hello");
}

// ---------------------------------------------------
// my_circle_bang
// ---------------------------------------------------
void my_circle_bang_method(t_my_circle *x){
   if(x->value == 0){
      sys_vgui(".x%lx.c itemconfigure %xrr -fill #00FF00 -outline #00FF00\n",
         x->glist,
         x
         );
      x->value = 1;
   }else{
      sys_vgui(".x%lx.c itemconfigure %xrr -fill #FF0000 -outline #FF0000 \n",
         x->glist,
         x
         );
      x->value = 0;
   }
}

//GUI stuff ---------------------------------------
// ---------------------------------------------------
// The external GUI rectangle definition
// ---------------------------------------------------
static void my_circle_getrect(t_gobj *z, t_glist *glist, int *xp1, int *yp1, int *xp2, int *yp2){
   // This function is always called. 
   // Better do not put a post here...
   // post("GETRECT");
   (void) glist;
   t_my_circle *x = (t_my_circle *)z;
   *xp1 = x->x_obj.te_xpix;
   *yp1 = x->x_obj.te_ypix;
   *xp2 = x->x_obj.te_xpix + 50;
   *yp2 = x->x_obj.te_ypix + 50;
}

// ---------------------------------------------------
// How to make it visible / invisible
// ---------------------------------------------------
static void my_circle_vis(t_gobj *z, t_glist *glist, int vis){
   t_my_circle *x = (t_my_circle *)z;
   t_canvas * canvas = glist_getcanvas(glist);
   if(vis){ // VISIBLE
      sys_vgui(".x%lx.c create oval %d %d %d %d -tags %xrr -outline #FF0000 -fill #FF0000\n",
		glist_getcanvas(glist),
		x->x_obj.te_xpix,
		x->x_obj.te_ypix,
		x->x_obj.te_xpix + 50,
		x->x_obj.te_ypix + 50,
		x
		);
   }else{
		sys_vgui(".x%x.c delete %xrr\n",canvas, x);
   }
}
// ---------------------------------------------------
// what to do when moved
// ---------------------------------------------------
static void my_circle_displace(t_gobj *z, t_glist *glist,int dx, int dy){
   t_canvas * canvas = glist_getcanvas(glist);
   t_my_circle *x = (t_my_circle *)z;
   x->x_obj.te_xpix += dx; // x movement
   x->x_obj.te_ypix += dy; // y movement
   //Move object representing selection (The blue one!)
   //Move object itself
   sys_vgui(".x%lx.c coords %xSEL %d %d %d %d \n", //MOVE O SELECIONADO
		canvas,
		x,
		x->x_obj.te_xpix,
		x->x_obj.te_ypix,
		x->x_obj.te_xpix + 50,
		x->x_obj.te_ypix + 50
		);
      sys_vgui(".x%x.c coords %xrr %d %d %d %d\n",
      canvas,
      x,
      x->x_obj.te_xpix,
      x->x_obj.te_ypix,
      x->x_obj.te_xpix + 50,
      x->x_obj.te_ypix + 50
      );
   canvas_fixlinesfor(glist, (t_text *)x);
}
// ---------------------------------------------------
// What to do when active
// ---------------------------------------------------
static void my_circle_activate(t_gobj *x, struct _glist *glist, int state){
   (void) x;
   (void) glist;
   (void) state;
}
// ---------------------------------------------------
// What to do when selected
// ---------------------------------------------------
static void my_circle_select(t_gobj *z, t_glist *glist, int state){
   t_my_circle *x = (t_my_circle *)z;
 	if (state) {
        sys_vgui(".x%x.c create oval %d %d %d %d -tags %xSEL -outline blue\n",
		glist_getcanvas(glist),
		x->x_obj.te_xpix,
		x->x_obj.te_ypix,
		x->x_obj.te_xpix + 50,
		x->x_obj.te_ypix + 50,
		x
		);
	}else {
 	sys_vgui(".x%x.c delete %xSEL\n",glist_getcanvas(glist), x);
	}
}
// ---------------------------------------------------
// What to do when clicked
// ---------------------------------------------------
static int my_circle_click(t_gobj *z, struct _glist *glist, int xpix, int ypix, int shift, int alt, int dbl, int doit){
   (void) xpix;
   (void) ypix;
   (void) shift;
   (void) alt;
   (void) dbl;
   (void) doit;
return 0;
}
// ---------------------------------------------------
// What to do when deleted
// ---------------------------------------------------
static void my_circle_delete(t_gobj *z, t_glist *glist){
   t_text *x = (t_text *)z;
   canvas_deletelinesfor(glist_getcanvas(glist), x);
   //post("Object deleted!");
   //Something else?
}
// ---------------------------------------------------
// What to do when saved
// ---------------------------------------------------
static void my_circle_save(t_gobj *c, t_binbuf *b){
   (void) c;
   (void) b;
}
// ---------------------------------------------------
// The properties window
// ---------------------------------------------------
static void my_circle_properties(t_gobj *c, t_glist *list){
   (void) c;
   (void) list;
}
//EOF GUI stuff --------------------------------------
// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void my_circle_setup(void) {
   my_circle_class = class_new(gensym("my_circle"),
      (t_newmethod) my_circle_new, // Constructor
      (t_method) my_circle_destroy, // Destructor
      sizeof (t_my_circle),
      CLASS_DEFAULT,
      0);//Must always ends with a zero

   class_addbang(my_circle_class, my_circle_bang_method);

//   GUI STUFF---------------------------
   my_circle_widgetbehavior.w_getrectfn = my_circle_getrect;
   my_circle_widgetbehavior.w_visfn= my_circle_vis;
   my_circle_widgetbehavior.w_displacefn= my_circle_displace;
   my_circle_widgetbehavior.w_selectfn= my_circle_select;
   my_circle_widgetbehavior.w_activatefn = my_circle_activate;
   my_circle_widgetbehavior.w_deletefn = my_circle_delete;
   my_circle_widgetbehavior.w_clickfn = my_circle_click;
//   class_setpropertiesfn(my_circle_class, my_circle_properties);
//   class_setsavefn(my_circle_class, my_circle_save);
   class_setwidget(my_circle_class, &my_circle_widgetbehavior);
}
// EOF---------------------------------------------------
