/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"
#include "g_canvas.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *my_rect_class;
t_widgetbehavior my_rect_widgetbehavior; // This represents the external GUI

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _my_rect {
   t_object x_obj;
} t_my_rect;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * my_rect_new(void);// Constructor
void my_rect_destroy(t_my_rect *x); //Destructor
//GUI stuff
static void my_rect_getrect(t_gobj *z, t_glist *glist, int *xp1, int *yp1, int *xp2, int *yp2);
static void my_rect_vis(t_gobj *z, t_glist *glist, int vis);
static void my_rect_displace(t_gobj *z, t_glist *glist,int dx, int dy);
static void my_rect_activate(t_gobj *x, struct _glist *glist, int state);
static void my_rect_select(t_gobj *z, t_glist *glist, int state);
static int my_rect_click(t_gobj *z, struct _glist *glist, int xpix, int ypix, int shift, int alt, int dbl, int doit);
static void my_rect_delete(t_gobj *z, t_glist *glist);

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * my_rect_new(void){
   t_my_rect *x = (t_my_rect *) pd_new(my_rect_class);

   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void my_rect_destroy(t_my_rect *x) {
   post("You say good bye and I say hello");
}

//GUI stuff ---------------------------------------
// ---------------------------------------------------
// The external GUI rectangle definition
// ---------------------------------------------------
static void my_rect_getrect(t_gobj *z, t_glist *glist, int *xp1, int *yp1, int *xp2, int *yp2){
   // This function is always called. 
   // Better do not put a post here...
   // post("GETRECT");
   t_my_rect *x = (t_my_rect *)z;
   *xp1 = x->x_obj.te_xpix;
   *yp1 = x->x_obj.te_ypix;
   //*xp2 = x->x_obj.te_xpix + 30; //width = 30
   //*yp2 = x->x_obj.te_ypix + 50; // height = 50
}
// ---------------------------------------------------
// How to make it visible / invisible
// ---------------------------------------------------
static void my_rect_vis(t_gobj *z, t_glist *glist, int vis){
   t_my_rect *x = (t_my_rect *)z;
   t_canvas * canvas = glist_getcanvas(glist);
   if(vis){ // VISIBLE
      //DRAW OBJECTS
      post("VISIBLE");
   }else{
      //DELETE OBJECTS
      post("INVISIBLE");
   }
}
// ---------------------------------------------------
// what to do when moved
// ---------------------------------------------------
static void my_rect_displace(t_gobj *z, t_glist *glist,int dx, int dy){
   post("MOVED");
   t_canvas * canvas = glist_getcanvas(glist);
   t_my_rect *x = (t_my_rect *)z;
   x->x_obj.te_xpix += dx; // x movement
   x->x_obj.te_ypix += dy; // y movement
   //Move object representing selection (The blue one!)
   //Move object itself
   canvas_fixlinesfor(glist, (t_text *)x);
}
// ---------------------------------------------------
// What to do when active
// ---------------------------------------------------
static void my_rect_activate(t_gobj *x, struct _glist *glist, int state){
   post("Activated %d", state);
}
// ---------------------------------------------------
// What to do when selected
// ---------------------------------------------------
static void my_rect_select(t_gobj *z, t_glist *glist, int state){
   t_my_rect *x = (t_my_rect *)z;
   if (state) {
      post("SELECTED");
      // We use to draw a blue contour here
   }else {
      post("DESELECTED");
      // We use to delete the blue contour here
   }
}
// ---------------------------------------------------
// What to do when clicked
// ---------------------------------------------------
static int my_rect_click(t_gobj *z, struct _glist *glist, int xpix, int ypix, int shift, int alt, int dbl, int doit){
post("Clicked xpix:%d ypix:%d shift:%d alt:%d dbl:%d doit:%d", xpix,ypix, shift, alt, dbl, doit);
return 0;
}
// ---------------------------------------------------
// What to do when deleted
// ---------------------------------------------------
static void my_rect_delete(t_gobj *z, t_glist *glist){
   t_text *x = (t_text *)z;
   canvas_deletelinesfor(glist_getcanvas(glist), x);
   //post("Object deleted!");
   //Something else?
}
//EOF GUI stuff ---------------------------------------
// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void my_rect_setup(void) {
   my_rect_class = class_new(gensym("my_rect"),
      (t_newmethod) my_rect_new, // Constructor
      (t_method) my_rect_destroy, // Destructor
      sizeof (t_my_rect),
      CLASS_DEFAULT,
      0);//Must always ends with a zero

//   GUI STUFF---------------------------
   my_rect_widgetbehavior.w_getrectfn = my_rect_getrect;
   my_rect_widgetbehavior.w_visfn= my_rect_vis;
   my_rect_widgetbehavior.w_displacefn= my_rect_displace;
   my_rect_widgetbehavior.w_selectfn= my_rect_select;
   my_rect_widgetbehavior.w_activatefn = my_rect_activate;
   my_rect_widgetbehavior.w_deletefn = my_rect_delete;
   my_rect_widgetbehavior.w_clickfn = my_rect_click;
   class_setwidget(my_rect_class, &my_rect_widgetbehavior);
}
// EOF---------------------------------------------------
